"""Add role fields to users table

Revision ID: 141ed4bc8cef
Revises: 001_initial_schema
Create Date: 2025-08-31 23:46:14.568857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '141ed4bc8cef'
down_revision = '001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add role fields to users table
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###